

  [build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist/content-hub-frontend"


[build.environment]
  NODE_VERSION = "22.x"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
