[build]
  command = "npx ng build --configuration production"
  publish = "dist/content-hub-frontend/browser"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
